

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - mongo1-data:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - mongo2-data:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - mongo3-data:/data/db
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0", "--bind_ip_all"]

  mongo-setup:
    image: mongo:6.0
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster
    entrypoint: >
      bash -c '
        sleep 5;
        echo "Initiating replica set...";
        mongosh --host mongo1:27017 <<EOF
          rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongo1:27017" },
              { _id: 1, host: "mongo2:27017" },
              { _id: 2, host: "mongo3:27017" }
            ]
          });
        EOF
        sleep infinity;
      '

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

networks:
  mongo-cluster:
    driver: bridge
